name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Test Backend
      run: |
        cd student-portal-backend
        ./mvnw clean verify
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: student-portal-frontend/package-lock.json
    
    - name: Install Frontend Dependencies
      run: |
        cd student-portal-frontend
        npm ci
    
    - name: Setup Test Environment
      run: |
        cd student-portal-frontend
        mkdir -p src/__mocks__
        echo "const mockAxios = {
          create: jest.fn(() => mockAxios),
          get: jest.fn(() => Promise.resolve({ data: {} })),
          post: jest.fn(() => Promise.resolve({ data: {} })),
          put: jest.fn(() => Promise.resolve({ data: {} })),
          delete: jest.fn(() => Promise.resolve({ data: {} })),
          defaults: { headers: { common: {} } }
        }; module.exports = mockAxios;" > src/__mocks__/axios.js
    
    - name: Test Frontend
      run: |
        cd student-portal-frontend
        npm test -- --watchAll=false
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Backend Image
      uses: docker/build-push-action@v4
      with:
        context: ./student-portal-backend
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/student-portal-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./student-portal-frontend
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/student-portal-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 